name: "Feature request"
description: "Suggest an idea or mechanic to add or remove from the server"
title: "[Feature] Cheese burgers"
labels: ["feature"]
assignees: ["McSnurtle"]
projects: ["McSnurtle/1"]

body:
  - type: markdown
    id: warning
    attributes:
      value: |
        **Before submitting this feature request:** ensure that this idea has not been submitted already.
  - type: textarea
    id: description
    attributes:
      label: "Describe the feature"
      description: |
        A clear and concise description of what you would like to see added / removed and why.
      placeholder: |
        Cheese burgers would be edible items, craftable and able to be automated, found occasionally in village chests and sold by farmers.
    validations:
      required: true
  - type: textarea
    id: problems
    attributes:
      label: "What problems does this feature solve / cause?"
      description: |
        Describe the problems the feature would solve, or cause for the player.
      placeholder: |
        Solves the issue of not finding enough food from Farmer's Delight in village chests.
    validations:
      required: true
  - type: dropdown
    id: systems
    attributes:
      label: "Which pre-existing system does this feature tie into?"
      description: |
        What systems would obviously conflict with or impede the implementation / removal of this feature?
      multiple: true
      options:
        - Terrain
        - Structure generation
        - Gameplay balancing
        - Recipes
        - UI
        - Mod compatibility
        - Other
        - N/A
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: |
        Attach screenshots or additional details to demonstrate your feature. If possible, please attach the relevant resource such as the datapack or mod page here.
      placeholder: "[Beesechurger](<https://www.curseforge.com/minecraft/mc-mods/embeddium>)"
    validations:
      required: false
