blank_issues_enabled: false
contact_links:
  - name: Skyfal Discord Support
  - url: https://discord.gg/TTdAB8emSp
  - about: The public \#help channel of the Skyfall Discord server. Read the description carefully!
