name: Bug report
description: Report a bug or problem with the software
title: "[Bug] chart scaling reseting on chart updates"
labels: ["bug"]
projects: ["McSnurtle/3"]
assignees: ["McSnurtle"]

body:
  - type: markdown
    id: warning
    attributes:
      value: |
        **Before filling out this issue form:** Ensure you have downloaded and are using the latest version of the software.
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: A clear and concise description of what the bug is and affects.
      placeholder: Every time the chart view updates to show more / new data, the scaling (changed by dragging the price value bar on the right-hand side) is reset to it's default, auto-scale self again.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce the behaviour:"
      placeholder: |
        1. Adjust scaling 
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: "Release"
      description: "What version of the program were you using (the version number from the latest changelog, i.e. v1.8)"
      placeholder: "vX.Y.Z"
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: "Expected Behaviour"
      description: "A clear and concise desription of what you expected to / should happen."
      placeholder: "The chart scaling should persist refreshes, with auto-scaling being togglable via button + hotkey."
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Added notes or context surrounding the issue."
      value: "None"
      placeholder: "N/A"
    validations:
      required: false
